project:
  type: website

website:
  title: "ISSS624"
  navbar:
    left: 
      - text: Hands-on Exercises
        menu: 
          - text: Hands-on Ecercise 1 part 1
            href: Hands-on_Ex1.qmd
          - text: Hands-on Exercise 1 part 2
            href: Hands-on_Ex1_2.qmd
          - text: Hands-on Exercise 2
            href: Hands-on_Ex/hands-on_Ex2/Hands_on_Ex2.qmd
          - text: Hands-on Exercise 3
            href: Hands-on_Ex/hands-on_Ex3/Hands-on_Exercise3.qmd
          - text: Hands-on Exercise 4
            href: Hands-on_Ex/hands-on_Ex4/Hands-on_Exercise4.qmd
      - text: In class Exercises
        menu: 
          - text: In-class Ecercise 1
            href: In-class_Ex/In-class_Ex1/In-class_Exercise1.qmd
          - text: In-class Ecercise 2
            href: In-class_Ex/In-class_Ex2/In-class_Ecercise2.qmd 
          - text: In-class Ecercise 3
            href: In-class_Ex/In-class_Ex3/In-class_Exercise3.qmd
          - text: In-class Ecercise 4
            href: In-class_Ex/In-class_Ex4/In-class_Exercise4.qmd
          - text: In-class Ecercise 5
            href: In-class_Ex/In-class_Ex5/In-class_Exercise5.qmd
      - text: Take home Exercises
        menu: 
          - text: Take-home Ecercise 1
            href: Take-home_Ex/Take-home_Ex1/Take-home_Exercise1.qmd
          - text: Take-home Ecercise 2
            href: Take-home_Ex/Take-home_Ex2/Take-home_Exercise2.qmd
 
          
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: tango
    css: styles.css
    toc: true

editor: visual

